version: '3'
services:
  message-check-api:
    build: application/message-check-api
    container_name: message-check-api
    ports:
     - "1881:1880"
    volumes:
     - ./application/message-check-api/data:/data
     - ./messages:/messages

  web-app:
    build: application/web-app
    container_name: web-app
    ports:
     - "1880:1880"
    volumes:
     - ./application/web-app/data:/data
    depends_on:
      - database-server

  database-server:
    build: application/database-server
    container_name: database-server
    ports:
      - "27017:27017"
    volumes:
      - ./application/database-server/data:/data/db